### ISSUE TITLE
Decide on a consistent, machine-readable output format to return a game result from a server

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-py#25]
I think a json format like this would be OK:
```json
{
  "scores": [
    {"player1": 2},
    {"player2": 5}
  ],
  "time": 2000
}
```

A question that remains in how we tell players with the same name apart or what keys the scores dictionary will have. I think player-ids would be ideal but these would have to be returned from the `run_clients.py`. I propose the following:
```json
{
  "players": ["player-id1", "player-id2"]
}
```
The player-ids will be listed in the exact order they were given to `run_clients.py` as arguments.

**Comment by Belissimo-T** [comment]
@joendter @karl-zschiebsch What do you think?

**Comment by karl-zschiebsch** [comment]
Why not use grpc? This is already written in json.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch
> Why not use grpc? This is already written in json.
What do you mean? gRPC is not already written in JSON.

This json output is supposed to be read by an automated tournament utility. When using gRPC, how do you ensure that the last game result was actually recieved by the util before the server closed? I think it's cleaner this way.

**Comment by karl-zschiebsch** [comment]
The server don't closes when the game ends. It only stops the game. It is possible to ask after the tournement when the game ends or to just start a new game without relauching the server.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 
> The server don't closes when the game ends. 
Okay, that would make it possible.

> It is possible to ask after the tournement when the game ends or to just start a new game without relauching the server.

How is that possible? I would prefer this utility to be written in python. I think Java is a ~boilerplate driven language~ bit overkill.

**Comment by karl-zschiebsch** [comment]
The Server just has a game object. If you replace this object with a new game, after the old ended, you can just easily go to the next match. Note that each client must rejoin after this.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 

> The Server just has a game object. If you replace this object with a new game, after the old ended, you can just easily go to the next match. Note that each client must rejoin after this.

How can a sperate process make that happen? Wouldn't it be just easier to relauch the process?

Also, can you specify the address via the command line?
