### ISSUE TITLE
Remove relative drawing

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-py#30]
![image](https://user-images.githubusercontent.com/37810842/212766433-7253bcd4-2893-44cb-bce7-9d38b565f92c.png)

**Comment by Kiyotoko** [comment]
To say it directly, I don't see a reasen why we ever schould use something like this. Debug drawing is much more useful than relative drawing.

**Comment by Belissimo-T** [comment]
Let's remove this feature.
