### ISSUE TITLE
Which objects should be linked?

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-py#33]
@seekers-dev

Below is a simplified object model for the python interface.

```py
class Seeker:
    player: Player

class Player:
    seekers: list[Seeker]
    camp: Camp

class Camp:
    player: Player
```

Is there a need for these doubly linked structures? 
- `Seeker.player <-> Player.seekers`
- `Player.camp <-> Camp.player`

**Comment by karl-zschiebsch** [comment]
Player contains only a string that can be used to link to an entry in a map. The same case is for Seeker and Camp: they have only a String to link to the player.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 

> Player contains only a string that can be used to link to an entry in a map. The same case is for Seeker and Camp: they have only a String to link to the player.

That might be the optimal solution form a speed and elegance standpoint. This object, however, is also  supposed to be accessed by the AIs. I'd argue that that makes it harder for people that don't know python to learn to program.

**Comment by karl-zschiebsch** [comment]
You can link them or just ignore it in your server/client. I also just reference the object. But what you meen is the proto file. That is something else and only optimized for speed.

**Comment by Belissimo-T** [comment]
@karl-zschiebsch 

Okay, so I'll leave them linked.
