### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by Kiyotoko** [seekers-dev/seekers-py#58]
**Is your feature request related to a problem? Please describe.**
The original repo was named `seekers`. Because of a name clash with the java implementation, we renamed this repo. But after the java implementation moved to a server side implementation only, there is no longer any name clash.

**Describe the solution you'd like**
Rename this repository (currently: `seekers-py`) back to `seekers`.

**Describe alternatives you've considered**
An alternative would be to keep the current name or use another one.

**Additional context**
This was already mentioned on discord.

**Comment by Belissimo-T** [comment]
I strongly oppose this. Changing the name (and therefore origin url of all local git repos) is a hassle. What if we (or any random future contributor!) decide to add a client implementation to [seekers-server](https://github.com/seekers-dev/seekers-server) (which shouldn't have been renamed, according to me!)? I think it's better to stick with the more general name.

**Comment by Kiyotoko** [comment]
Ok, I will close this issue then as won't fix
