### ISSUE TITLE
No newline at end of `config.ini`

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-py#61]
**Describe the bug**
The file `config.ini` does not end in a newline.
All text files should end with a newline. 
See https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

**Comment by Supergecki** [comment]
And, for the future, I have the feeling it might make sense to not add the "confirmed" label yourself as confirmation should involve at least a second person.

**Comment by Belissimo-T** [comment]
@Supergecki You're right, there is a newline :sob:.
